<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>Thomas Oberbichler</Authors>
    <Company>Thomas Oberbichler</Company>
    <Copyright>Copyright © 2026 Thomas Oberbichler</Copyright>
    <Description>A blazing fast, zero-allocation C# port of Mapbox Polylabel for finding the pole of inaccessibility of a polygon.</Description>
    <PackageLicenseExpression>ISC</PackageLicenseExpression>
  </PropertyGroup>

</Project>
